### ISSUE TITLE
Can't see the processing code for HEXOME Simulator. Advertised as being here

### ISSUE THREAD

**Issue by rbnpi** [Grumpy-Mike/Mikes-Pi-Bakery#1]
Title says it all!

**Comment by Grumpy-Mike** [comment]
Yes the magazine is out tomorrow so the code will be put on my GitHub tonight along with a video.
Cheers
Mike

Sent from my iPad

**Comment by rbnpi** [comment]
OK I guess the subscription ones (mine arrived today) come out a day early.
I've built the TouchOSC interface. Quite quick using copy and paste and distribute controls. I want to try and use it with Sonic Pi the dev version of which (due to be released at end of June) allows OSC inputs. I've already built Touch OSC keyboard and midi controller for it.

**Comment by Grumpy-Mike** [comment]
OK on line now.
Hope you like it.

**Comment by rbnpi** [comment]
Thanks

**Comment by rbnpi** [comment]
Got it working nicely now. (Running it entirely on a Mac, although tried on my Pi as well). I think the write up omits to show the adding of the push buttons underneath the leds on TouchOSCn in the three steps shown to build the interface. Of course you can get them if you download the finished file.
I am now working on converting it for Sonic Pi use. SP doesn't accept external OSC message input as easily (although its fine on OSC output), but does accept midi input, so I've added midi cc messages from the push buttons, toggles and faders, and this is working OK. Now about to work on converting the processing logic to work in SP.

**Comment by Grumpy-Mike** [comment]
Hi Rob,
Thanks for that, I appreciate the feed back.
Yes it would be good to know if you get it working on sonic Pi because that might fit in with the project for the next magazine which is a wind chimes program written in Python.
Sorry for not posting the code immediately yesterday afternoon on your first message but I was in the Bridge Inn in Buttermere ( Lake District ) and only had my iPad.
Cheers and keep me posted
Mike

**Comment by rbnpi** [comment]
No problem. Envious of a pub visti to Buttermere:-) The Sonic Pi stuff won't work until the next version is released at the end of June, although you can get a prerelease by supporting Sam Aaron via Patreon site. (or compile it yourself :-)  You can have lots of other fun with the hexome besides your project. So far I've been flashing leds selected by notes from SP, and produced various rotating patterns.

**Comment by rbnpi** [comment]
Hi Mike
I now have it working fully driven by Sonic Pi(2.12 dev-midi-alpha5 version) instead of Processing. The only screen output is now TouchOSC. I am using your samples to produce the sound, played by Sonic Pi which is also handling all the logic. Quite fun doing the translation, but as your code was clear and easy to follow it wasn't too bad to do. Driving from my Mac so far. Haven't tried it on a Pi yet.
