### ISSUE TITLE
setMinimumTouchSize correct?

### ISSUE THREAD

**Issue by Heerkog** [Grumpy-Mike/Mikes-Pi-Bakery#4]
Hey,

I'm using your library to implement a MicroPython version and I was curious about whether the setMinimumTouchSize function is correct.

An excerpt:
```
        maxMinSize = (1 << 16) - 1

        if(maxMinSize > minSize / self.sizeRescale): 
            minSize = maxMinSize # clip to max value we can send
        else: 
            size = minSize / self.sizeRescale        

        block[kCommandMinimumSize, size >> 8, size & 0xFF]
```

To me it seems like
(i) we are checking if the max is larger than the scaled value. Then if it is larger, we set the value to max. Should we not set the value to max if the scaled value is larger instead?
(ii) Should we not assign max to the variable size? Otherwise, when the if evaluates to True, we never initialize size.

Should it not be this?
```
        maxMinSize = (1 << 16) - 1
        minSize = minSize / self.sizeRescale
        size = minSize if maxMinSize > minSize else maxMinSize
        block[kCommandMinimumSize, size >> 8, size & 0xFF]
```

Cheers

**Comment by Grumpy-Mike** [comment]
Hi Heerko,
Thanks for this. What I was trying to do was to convert the original Trill library from C++ into Python.
The original code was:-

int Trill::setMinimumTouchSize(float minSize) {
	unsigned int bytesToWrite = 4;
	uint16_t size;
	float maxMinSize = (1<<16) - 1;
	if(maxMinSize > minSize / sizeRescale) // clipping to the max value we can transmit
		minSize = maxMinSize;
	else
		size = minSize / sizeRescale;
	char buf[4] = { kOffsetCommand, kCommandMinimumSize, (char)(size >> 8), (char)(size & 0xFF) };
	if(int writtenValue = (::write(i2C_file, buf, bytesToWrite)) != bytesToWrite)
	{
		fprintf(stderr, "Failed to set Trill's minimum touch size value.\n");
		fprintf(stderr, "%d\n", writtenValue);
		return 1;
	}
	preparedForDataRead_ = false;
	usleep(commandSleepTime); // need to give enough time to process command

	return 0;
}

I was concentrating more on the syntax conversion rather that what the function appeared to say. That is in making the function do what the title said it should do.
I could be wrong with what I did but in my defence the library seemed to do everything it should do in python.
What do you think from the original code?
Thanks for bringing this to my attention.
Cheers
Mike

**Comment by Heerkog** [comment]
Seems to do the same indeed! Good job!

Is this a bug by Bela then? I mean, even when considering that maxMinSize could actually be meant as minMinSize, the size variable remains null when the if evaluates True.

Also, where do I find this source code? Having access to that would be really helpful!

**Comment by Grumpy-Mike** [comment]
Hi Heerko,

> Is this a bug by Bela then?
> 

Looks like it could be.

> where do I find this source code?
> 
Lots of good information here
https://learn.bela.io/products/trill/about-trill/ <https://learn.bela.io/products/trill/about-trill/> 
with the source code here

https://github.com/BelaPlatform/Trill-Arduino <https://github.com/BelaPlatform/Trill-Arduino>

I notice that the Trill.cpp file has been updated in the last month.

Cheers
Mike

**Comment by Heerkog** [comment]
The updated ccp seems very clean! Thanks!

**Comment by Grumpy-Mike** [comment]
Just realised that if you want a Micro Python version of this library I did one for the "Trill Part 3 Guitar 1" to use on the Pico 2040 in the MagPi # 104.
I had to make some modifications to how you searched the I2C bus.

**Comment by Heerkog** [comment]
That's great! Thank you for that!

I actually have a working version already for my square. I'm planning on adding classes for the other sensors before making it public.

If you're interested, I can send you a link the repository once I make it public!

**Comment by Grumpy-Mike** [comment]
Yes that would be good thanks.

**Comment by Heerkog** [comment]
https://github.com/Heerkog/MicroPythonTrill

I'll add a read me later. Enjoy!

**Comment by Heerkog** [comment]
```
from machine import SoftI2C, Pin
from trill import Square
from touch import Touches2D

i2c = SoftI2C(...)

s = Square(i2c)
data = s.read()
t = Touches2D(data)
print(t.getTouches())
```
